### ISSUE TITLE
Other versions

### ISSUE THREAD

**Issue by lcolladotor** [weitzner/jhu-thesis-template#2]
Hi,

I just finished making a template with a `makefile` based on https://github.com/muschellij2/PhD_Thesis. John Muschelli edited your template quite a bit and in particular also supports `Rnw` files for those of us that work with [R](https://cran.r-project.org/). The template I created is available at [lcolladotor/jhu-thesis-template](https://github.com/lcolladotor/jhu-thesis-template). It was easier to fork Muschelli's version and go from there than to fork yours. I also added a read-only version at Overleaf available [here](https://www.overleaf.com/read/tqdzgmrxgbtg) and submitted it to their gallery as a template.

After doing so, I noticed that the Overleaf gallery has already a template based on your version. It was submitted by Karla Hernandez on March 2016 and is available [here](https://www.overleaf.com/latex/templates/johns-hopkins-phd-dissertation-template/jmdrczzbrhyx#.Vw7LVhMrL64).

Anyhow, the advantage of using Overleaf (or ShareLatex) is that you don't need a full LaTeX installation on your computer.

Best,
Leonardo

**Comment by weitzner** [comment]
I’m glad folks are continuing to make improvements and keep the template widely available! Since the JHU library links to this repo, it might make sense to open a pull request for your changes or to otherwise coordinate to get the more flexible version up here.
